#!/bin/bash 
#
# Author:
#  Walter Phippeny      
# Date:
#  09 01 2011
# Description:
# This script deals with external backup procedures 
#  
# $Header: /vol/src/extback/RCS/extback,v 1.3 2011/09/23 03:46:38 walterp Exp $
#

bkmnt=/vol/backups
extmnt=/media/extback
bkdir=$extmnt/backups
tar=$bkdir/backups.tar
mailaddrs="habeascorpus@digitalhecatomb.net"
logfile=/var/log/extback.log

 function myexit {
   date=`date "+%m/%d/%Y %H:%M:%S"`
   cat $tmpfile | sed -e "s=^=$date =g" >>$logfile
   cat <<EOD | cat -  $tmpfile | mailx -s "$program - $2" $mailaddrs
   `date`
   hostname=`hostname`
   program=$0

EOD
   umount $extmnt 2>/dev/null
   rm -f $tmpfile
   exit $1
}
    
program=`basename $0` 
tmpfile="/tmp/$program.$$"

#error check to verify that NAS is mounted

/bin/ls $bkmnt > /dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  cat >$tmpfile <<EOD 
  ERROR: NAS is not mounted 
  bkmnt=$bkmnt 
EOD
  myexit 2 "ERROR: NAS is not mounted"
fi

/bin/ls $bkdir > /dev/null 2>/dev/null
if [ $? -ne 0 ]; then
  mount /dev/sdb1 $extmnt 2>/dev/null
  if [ $? -ne 0 ]; then
     cat >$tmpfile <<EOD 
     ERROR: USB drive is not mounted
     extmnt=$extmnt
EOD
     myexit 3 "ERROR: USB drive is not mounted"
  fi   
fi

bktime=`(time tar -cf $tar $bkmnt) 2>&1 | grep real | awk '{print $2}'`
bktar=`(time tar -tf $tar > /dev/null) 2>&1 | grep real | awk '{print $2}'`
if [ $? -ne 0 ]; then
  cat >$tmpfile <<EOD
  ERROR: Index of tar file failed
  tar=$tar
EOD
  myexit 4 "ERROR: Index of tar file failed"
fi

cat >$tmpfile <<EOD
$program for external backup rotation completed successfully 
Back up time = $bktime
Tar verification time = $bktar
EOD
myexit 0 "completed successfully"
